name: project_x
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cloud_firestore: ^4.4.3
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  firebase_auth: ^4.2.8
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_barcode_scanner: ^2.0.0
  flutter_facebook_auth: ^5.0.7
  flutter_google_places: ^0.3.0
  flutter_google_places_hoc081098: ^1.0.0-nullsafety.1
  flutter_native_splash: ^2.2.17
  flutter_polyline_points: ^1.0.0
  get: ^4.6.5
  google_maps_flutter: ^2.2.4
  google_place: ^0.4.7
  google_sign_in: ^6.0.1
  http: ^0.13.5
  location: ^4.4.0
  mpesa_flutter_plugin: ^1.6.1
  path_provider: ^2.0.13
  provider: ^6.0.5
  share: ^2.0.4
  qr_flutter: ^4.0.0
  shared_preferences: ^2.0.17
  uuid: ^3.0.7
  qrscan: ^0.3.3

dev_dependencies: null
# flutter_launcher_icons: "^0.11.0"
flutter_native_splash:
  color: "#D3D3D3"
  # color_dark: "#000000"
  image: assets/images/logo.png
  # image_dark: assets/images/logo_dark.jpg
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icons/logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  fonts:
    - family: Muli
      fonts:
        - asset: assets\fonts\muli\Muli.ttf
        - asset: assets\fonts\muli\Muli-Bold.ttf
          weight: 700
        - asset: assets\fonts\muli\Muli-Light.ttf
          weight: 300
